### ISSUE TITLE
Charity registration - integrate API for charity-meta profile, wallet, key-person profile details

### ISSUE THREAD

**Issue by ghost** [AngelProtocolFinance/angelprotocol-web-app#154]
- [x] complete the key-person UI
- [x] complete the key-person API integration
- [x] complete the charity-meta data UI
- [x] complete the charity-meta data API integration
- [x] complete the wallet UI
- [x] complete the wallet API integration
