### ISSUE TITLE
EPIC: Polygon Admin wiring for Solidity contracts

### ISSUE THREAD

**Issue by SovereignAndrey** [AngelProtocolFinance/angelprotocol-web-app#1865]
If the endowment owner is connected with an EVM wallet on Polygon network, our web app needs to allow them to sign the EVM contract equivalent messages that we have today for the Cosmos contracts. This includes the following sub-tasks and requirements:

## WebApp
- [ ] logic to check the wallet used and set correct messages "middleware" to use (Cosmos vs EVM)
- [ ] all Applications / AP Team messages (proposal creation / voting)
- [ ] all Endowment Admin messages (withdraw / proposal creation / voting)
- [ ] off line signing for profile updates

## AWS
- [ ] AWS creation of applications (Charity) on Polygon (proposal)
- [ ] AWS member checks and offline signing checks

## Solidity Contracts
- can be found at TBA repo once completed (this is the main blocker to starting this Epic.
